version: '3.8'

services:
  job-service-db:
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: waw-jobs

  job-service:
    image: waw-job-service
    build:
      context: waw-job-service/waw-job-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DbConnectionString=Server=job-service-db;Port=3306;Database=waw-jobs;Uid=root;Pwd=admin
    depends_on:
      - job-service-db

  api-gateway:
    image: waw-api-gateway
    build:
      context: api-gateway/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    links:
      - job-service
      - auth-service
      - chat-service
      - employer-service
    depends_on:
      - job-service
      - auth-service
      - chat-service
      - employer-service

  auth-service-db:
    image: mysql:8.0.31
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: waw-auth

  auth-service:
    image: waw-auth-service
    build:
      context: waw-auth-service/waw-auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - DbConnectionString=Server=auth-service-db;Port=3306;Database=waw-auth;Uid=root;Pwd=admin
    depends_on:
      - auth-service-db

  chat-service-db:
    image: mysql:8.0.31
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: waw-chat

  chat-service:
    image: waw-chat-service
    build:
      context: waw-chat-service/waw-chat-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - DbConnectionString=Server=chat-service-db;Port=3306;Database=waw-chat;Uid=root;Pwd=admin
    depends_on:
      - chat-service-db

  employer-service-db:
    image: mysql:8.0.31
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: waw-employer

  employer-service:
    image: waw-employer-service
    build:
      context: waw-employer-service/waw-employer-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      - DbConnectionString=Server=employer-service-db;Port=3306;Database=waw-employer;Uid=root;Pwd=admin
    depends_on:
      - employer-service-db
